version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 127.0.0.0
    volumes:
      - .:.
    environment:
      - DATABASE_URL=postgresql+psycopg://test:test@localhost/testtaskgpn
    ports:
      - 8008:8000

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=testtaskgpn

volumes:
  postgres_data: