CREATE TABLE "devices" (
  "id" integer PRIMARY KEY,
  "name" varchar(100) NOT NULL
);

CREATE TABLE "Value" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "device_id" integer,
  "x" float NOT NULL,
  "y" float NOT NULL,
  "z" float NOT NULL,
  "time" timestamp NOT NULL
);

ALTER TABLE "Value" ADD FOREIGN KEY ("device_id") REFERENCES "devices" ("id");
